default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sonosweb-rails_development

test:
  <<: *default
  database: sonosweb-rails_test

production:
  <<: *default
  database: sonosweb-rails_production
  username: 
  password: 